error_msg:
  not_logged_in: 'Please login with your tadl.org username.'
  invalid_domain: 'Only valid tadl.org users may login to this application.'
  not_supper_user: 'You do not have rights to access this page'