:schedule:
  fetch_trailers:
    every: '30m'
    class: FetchTrailers
  fetch_posts:
    every: '15m'
    class: FetchPosts
  fetch_events:
    every: '15m'
    class: FetchEvents
  fetch_sign:
    every: '15m'
    class: FetchSign
  fetch_workorders:
    every: '3m'
    class: FetchWorkorders